name: mxcl/Xcodebuild
author: Max Howell
description: A continuously resilient `xcodebuild` action
inputs:
  xcode:
    description: |
      A semantic-version, eg. ^10, ~10.3 or 10.3.1
      Leave unset for the image‑default.
    required: false
  swift:
    description: A semantic-version, eg. ^5, ~5.4 or 5.4.1
    required: false
  platform:
    description: |
      Either `iOS`, `tvOS`, `macOS` or `watchOS`
      Leave unset and `xcodebuild` decides itself.
    required: false
  action:
    description: |
      The most common actions are `test`, `build`.
      See the `xcodebuild` manual for available actions.
    required: false
    default: test
  code-coverage:
    description: Enables code coverage
    required: false
    default: false
  working-directory:
    description: '…'
    required: false
  quiet:
    description: Only output errors
    required: false
  configuration:
    description: |
      Typically `Release` or `Debug`.
      Leave unset and `xcodebuild` decides itself.
    required: false
  warnings-as-errors:
    description: Fails the build if any warnings in *non test targets*.
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
