on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 37 11 * * *
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  verify:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - tvOS
          - watchOS
          - macOS
        xcode:
          - ^10
          - ^11
          - ^12
        codecov:
          - true
          - false
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
