on: pull_request
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  defaults:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          working-directory: fixture/debug

  configurations:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
          - debug
          - release
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          configuration: ${{ matrix.configuration }}
          working-directory: fixture/${{ matrix.configuration }}
          warnings-as-errors: true
          action: test

  verify:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - macOS
          - watchOS
        xcode:
          - ^10
          - ^11
        codecov:
          - false
        action:
          - test
        errors-as-warnings:
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        errors-as-warnings: ${{ matrix.errors-as-warnings }}

  verify2:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - watchOS
        xcode:
          - ^12
        codecov:
          - false
        action:
          - build
          - test
        errors-as-warnings:
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        errors-as-warnings: ${{ matrix.errors-as-warnings }}

  verify3:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}}${{ matrix.errors-as-warnings && ', errors-as-warnings' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - macOS
        xcode:
          - ^12
        codecov:
          - true
          - false
        action:
          - build
          - test
        errors-as-warnings:
          - true
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        errors-as-warnings: ${{ matrix.errors-as-warnings }}
