on:
  pull_request:
    paths:
      - '*.ts'
      - .github/workflows/checks.yml
      - dist/*
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  defaults:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          working-directory: fixture/debug

  configurations:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
          - debug
          - release
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          configuration: ${{ matrix.configuration }}
          working-directory: fixture/${{ matrix.configuration }}
          warnings-as-errors: true
          action: test

  swift:
    runs-on: macos-10.15
    strategy:
      matrix:
        swift:
          - ~5.0
          - ~5.1
          - ~5.2
          - ~5.3
          - ~5.4
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        swift: ${{ matrix.swift }}
        working-directory: fixture/swift/${{ matrix.swift }}
        action: build
      continue-on-error: ${{ matrix.swift == '~5.4' }}

  xcode:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - macOS
          - watchOS
        xcode:
          - ^10
          - ^11
        codecov:
          - false
        action:
          - test
        warnings-as-errors:
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        warnings-as-errors: ${{ matrix.warnings-as-errors }}

  more-xcode:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - watchOS
        xcode:
          - ^12
        codecov:
          - false
        action:
          - build
          - test
        warnings-as-errors:
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        warnings-as-errors: ${{ matrix.warnings-as-errors }}

  verify3:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}}${{ matrix.warnings-as-errors && ', warnings-as-errors' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - macOS
        xcode:
          - ^12
        codecov:
          - true
          - false
        action:
          - build
          - test
        warnings-as-errors:
          - true
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        warnings-as-errors: ${{ matrix.warnings-as-errors }}
