on:
  pull_request:
    paths:
      - '*.ts'
      - 'fixtures/**/*.swift'
      - .github/workflows/checks.yml
      - dist/*
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  defaults:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          working-directory: fixtures/debug

  configurations:
    runs-on: macos-10.15
    strategy:
      matrix:
        configuration:
          - debug
          - release
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          configuration: ${{ matrix.configuration }}
          working-directory: fixtures/${{ matrix.configuration }}
          warnings-as-errors: true
          action: test

  swift:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - swift: ~5.0
            os: macos-10.15
          - swift: ~5.1
            os: macos-10.15
          - swift: ~5.2
            os: macos-10.15
          - swift: ~5.3
            os: macos-10.15
          - swift: ~5.4
            os: macos-11
          - swift: ~5.5
            os: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        swift: ${{ matrix.swift }}
        working-directory: fixtures/swift/${{ matrix.swift }}
        action: build
    - uses: mxcl/get-swift-version@v1
      with:
        requires: ${{ matrix.swift }}

  xcode:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}})
    runs-on: ${{ matrix.os || 'macos-11' }}
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - macOS
          - watchOS
        xcode:
          - ^10
          - ^11
          - ^12
          - ^13
        codecov:
          - false
        action:
          - test
        warnings-as-errors:
          - false
        include:
          - xcode: ^10
            os: macos-10.15
          - platform: mac-catalyst
            xcode: ^13
            codecov: false
            action: test
            warnings-as-errors: false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixtures/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        warnings-as-errors: ${{ matrix.warnings-as-errors }}

  more-xcode:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11
        platform:
          - watchOS
        xcode:
          - ^12
        codecov:
          - false
        action:
          - build
          - test
        warnings-as-errors:
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixtures/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        warnings-as-errors: ${{ matrix.warnings-as-errors }}

  verify-codecov:
    name: ${{ matrix.platform }} (${{ matrix.action }}, ${{ matrix.xcode }}${{ matrix.codecov && ', cc' || ''}}${{ matrix.warnings-as-errors && ', warnings-as-errors' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - macOS
        xcode:
          - ^12
        codecov:
          - true
          - false
        action:
          - build
          - test
        warnings-as-errors:
          - true
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixtures/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
        warnings-as-errors: ${{ matrix.warnings-as-errors }}

  verify-swift-version:
    name: .swift-version
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/get-swift-version@v1
      with:
        requires: '>5.1'
    - uses: ./
      with:
        working-directory: fixtures/dot-swift-version
    - uses: mxcl/get-swift-version@v1
      with:
        requires: ~5.1
