on: pull_request
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  defaults:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          working-directory: fixture/debug

  configurations:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
          - debug
          - release
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          configuration: ${{ matrix.configuration }}
          working-directory: fixture/${{ matrix.configuration }}

  verify:
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - macOS
        xcode:
          - ^10
          - ^11
          - ^12
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}

  # watchOS has more complexity, so we need a larger matrix to ensure
  # we are covering all our code paths
  verify-watchos:
    name: verify (${{ matrix.platform }}, ${{ matrix.xcode }}, ${{ matrix.action }}${{ matrix.codecov && ', codecov' || ''}})
    runs-on: macos-10.15
    strategy:
      matrix:
        platform:
          - watchOS
        xcode:
          - ^10
          - ^11
          - ^12
        codecov:
          - true
          - false
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
        working-directory: fixture/${{ matrix.platform }}
        code-coverage: ${{ matrix.codecov }}
        action: ${{ matrix.action }}
